export const REGISTRATION_REQUEST_REPOSITORY = Symbol(
  'REGISTRATION_REQUEST_REPOSITORY',
);
export const ALUMNI_REPOSITORY = Symbol('ALUMNI_REPOSITORY');
export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const VERIFICATION_TOKEN_REPOSITORY = Symbol(
  'VERIFICATION_TOKEN_REPOSITORY',
);
export const PHOTO_UPLOAD_REPOSITORY = Symbol('PHOTO_UPLOAD_REPOSITORY');
export const ALUMNI_CARD_GENERATOR = Symbol('ALUMNI_CARD_GENERATOR');
export const NOTIFICATION_SENDER = Symbol('NOTIFICATION_SENDER');
export const PHOTO_STORAGE = Symbol('PHOTO_STORAGE');
